const CASE={suspects:["Dr. Evelyn Shaw","Daniel Price","Jonah Reed","Helena Vale","Prof. Simon Graves"]};
const phoneSections={
  "Messages":[
    {title:"Evelyn Shaw",detail:"21 NOV 2005 16:16\nEVELYN: We need to discuss this privately.\n\nADRIAN 16:18: Tonight. My house. 7:30.\n\nEVELYN 16:20: Please don't file anything until we talk.\n\nADRIAN 22:42: My decision stands."},
    {title:"Daniel Price",detail:"22 NOV 2005 13:08\nDANIEL: You have no idea how much damage this will do.\n\nADRIAN 13:11: I know exactly what it will do."},
    {title:"Jonah Reed",detail:"23 NOV 2005 21:44\nJONAH: Please give me until Monday.\n\nADRIAN 21:49: No. Friday."},
    {title:"Helena Vale",detail:"23 NOV 2005 19:18\nHELENA: Are you still sick?\n\nADRIAN 19:21: Much better today. Dinner is still happening."}
  ],
  "Call register":[
    {title:"22 NOV 08:14 — Dr. Keller",detail:"OUTGOING CALL\nDuration: 04:37"},
    {title:"21 NOV 19:28 — Evelyn Shaw",detail:"INCOMING CALL\nDuration: 00:21"},
    {title:"24 NOV 17:18 — BLOCKED",detail:"MISSED CALL"}
  ],
  "Calendar":[{title:"25 NOV 2005",detail:"09:00\nSubmit Research Integrity Packet\n\nE.S. / D.P. / J.R."}],
  "Notes":[
    {title:"Note 1",detail:"Friday. 9 AM. No more delays."},
    {title:"Note 2",detail:"If anything happens to me, check the archive record."},
    {title:"Note 3",detail:"Mom's birthday is still the only number I remember."}
  ],
  "Contacts":[
    {title:"Evelyn Shaw",detail:"Evelyn Shaw"},{title:"Daniel Price",detail:"Daniel Price"},{title:"Jonah Reed",detail:"Jonah Reed"},{title:"Helena Vale",detail:"Helena Vale"},{title:"Simon Graves",detail:"Simon Graves"},{title:"Dr. Keller",detail:"Dr. Keller"}
  ]
};
const phoneMenu=Object.keys(phoneSections);
let phoneState={mode:"menu",menuIndex:0,section:null,itemIndex:0};

function getBase(){const parts=location.pathname.split('/').filter(Boolean);return location.hostname.endsWith('github.io')&&parts.length?'/'+parts[0]:''}
function route(){let p=location.pathname,b=getBase();if(b&&p.startsWith(b))p=p.slice(b.length)||'/';return p.replace(/\/+$/,'')||'/'}
function gmOpen(path){location.replace(getBase()+path)}
function page(content,gm=false){document.getElementById('app').innerHTML=`<div class="shell">${gm?`<div class="gm-head"><div class="brand">CASE 112405 // GAME MASTER INDEX</div><div class="gm-only">GM ONLY</div></div>`:''}${content}</div>`}
function home(){page(`<div class="card"><div class="small">GAME MASTER ROUTE DIRECTORY</div><h1>CASE 112405</h1><p>Use these buttons only when setting up or testing NFC tags. Player-facing pages intentionally contain no global navigation.</p></div><div class="grid">
${[['Recovered Nokia','/phone'],['Purdue Archive','/purdue'],['Arthur Fungarium','/purdue/fungarium'],['Personnel Record','/purdue/personnel/eshaw'],['Campus Access','/purdue/access'],['Weather Archive','/archive/weather'],['Forensic Chemistry','/forensics/chemistry'],['Encrypted Files','/files'],['Final Terminal','/terminal']].map(([n,p])=>`<button class="linkcard" onclick="gmOpen('${p}')"><h3>${n}</h3><div class="small">${p}</div></button>`).join('')}</div>`,true)}

function phone(){phoneState={mode:'menu',menuIndex:0,section:null,itemIndex:0};page(`<div class="phone-wrap"><div><div class="nokia"><div class="nokia-brand">NOKIA</div><div class="screen" id="phoneScreen"></div><div class="dpad"><button class="up" onclick="phoneUp()">▲</button><button class="left" onclick="phoneBack()">◀</button><button class="ok" onclick="phoneOK()">OK</button><button class="right" onclick="phoneOK()">▶</button><button class="down" onclick="phoneDown()">▼</button></div><div class="keypad">${['1','2 ABC','3 DEF','4 GHI','5 JKL','6 MNO','7 PQRS','8 TUV','9 WXYZ','*','0','+ #'].map(x=>`<div class="key">${x}</div>`).join('')}</div></div><div class="phone-help">Use ▲ ▼ OK and ◀. The screen does not scroll.</div></div></div>`);renderPhone()}
function phoneHeader(name){return `<div class="screen-head"><span>${name}</span><span>▮▮ 17:42</span></div>`}
function renderPhone(){const s=document.getElementById('phoneScreen');if(!s)return;
 if(phoneState.mode==='menu')s.innerHTML=phoneHeader('Menu')+`<div class="phone-list">${phoneMenu.map((x,i)=>`<div class="phone-row ${i===phoneState.menuIndex?'selected':''}">${i+1} ${x}</div>`).join('')}</div><div class="softkeys"><span>Select</span><span></span></div>`;
 else if(phoneState.mode==='list'){const arr=phoneSections[phoneState.section];s.innerHTML=phoneHeader(phoneState.section)+`<div class="phone-list">${arr.map((x,i)=>`<div class="phone-row ${i===phoneState.itemIndex?'selected':''}">${x.title}</div>`).join('')}</div><div class="softkeys"><span>Open</span><span>Back</span></div>`}
 else {const item=phoneSections[phoneState.section][phoneState.itemIndex];s.innerHTML=phoneHeader(item.title)+`<div class="phone-detail">${item.detail.replace(/\n/g,'<br>')}</div><div class="softkeys"><span></span><span>Back</span></div>`}}
window.phoneUp=()=>{if(phoneState.mode==='menu')phoneState.menuIndex=(phoneState.menuIndex-1+phoneMenu.length)%phoneMenu.length;else if(phoneState.mode==='list'){let n=phoneSections[phoneState.section].length;phoneState.itemIndex=(phoneState.itemIndex-1+n)%n}else return;renderPhone()}
window.phoneDown=()=>{if(phoneState.mode==='menu')phoneState.menuIndex=(phoneState.menuIndex+1)%phoneMenu.length;else if(phoneState.mode==='list'){let n=phoneSections[phoneState.section].length;phoneState.itemIndex=(phoneState.itemIndex+1)%n}else return;renderPhone()}
window.phoneOK=()=>{if(phoneState.mode==='menu'){phoneState.section=phoneMenu[phoneState.menuIndex];phoneState.itemIndex=0;phoneState.mode='list'}else if(phoneState.mode==='list')phoneState.mode='detail';renderPhone()}
window.phoneBack=()=>{if(phoneState.mode==='detail')phoneState.mode='list';else if(phoneState.mode==='list'){phoneState.mode='menu';phoneState.section=null;phoneState.itemIndex=0}renderPhone()}

function purdue(){page(`<div class="paper"><div class="small">PURDUE UNIVERSITY // ARCHIVED INTRANET // 2005</div><h1>Biological Collections Portal</h1><p>Recovered mirror. Several records were damaged during archive recovery.</p><p><b>Collections:</b> Botany Herbarium / Arthur Fungarium / Teaching Collection / Plant Pathology Reference Sets</p><p><b>Building:</b> Lilly Hall of Life Sciences</p><p><b>System status:</b> READ ONLY</p></div>`)}
function fungarium(){page(`<div class="paper"><div class="small">ARTHUR FUNGARIUM // INTERNAL CATALOG MIRROR</div><h1>Recovered Catalog</h1><p><b>Collection area:</b> Restricted Teaching Collection, Cabinet F-12</p><p><b>Audit cycle:</b> Fall 2005 inventory reconciliation</p><table><tr><th>Accession</th><th>Taxon / Material</th><th>Collection</th><th>Status</th></tr><tr><td>PUR-F-77418</td><td><i>Ganoderma</i> sp.</td><td>Teaching ref.</td><td>Present</td></tr><tr><td>PUR-F-77419</td><td><i>Morchella</i> sp.</td><td>Teaching ref.</td><td>Present</td></tr><tr><td>PUR-F-77420</td><td><i>Coprinus</i> sp.</td><td>Teaching ref.</td><td>Present</td></tr><tr><td><b>PUR-F-77421</b></td><td><b><i>Amanita phalloides</i></b></td><td><b>Restricted teaching</b></td><td><b>RECORD DISCREPANCY</b></td></tr><tr><td>PUR-F-77422</td><td><i>Amanita muscaria</i></td><td>Teaching ref.</td><td>Present</td></tr><tr><td>PUR-F-77423</td><td><i>Claviceps</i> sp.</td><td>Historical ref.</td><td>Present</td></tr><tr><td>PUR-F-77424</td><td>Unknown basidiomycete</td><td>Teaching ref.</td><td>Present</td></tr></table><h3>Audit Notes</h3><ul><li>Cabinet F-12 requires staff credential access.</li><li>One catalog entry changed to discrepancy status after the 21 NOV 2005 audit.</li><li>Paper checkout card for accession 77421 is missing from the recovered box.</li><li>Electronic access record associated with this cabinet is incomplete.</li><li>Handling and specimen-preparation information is not included in this reconstruction.</li></ul><p><b>Last audit flag:</b> 21 NOV 2005</p><p><b>Related record:</b> Credential ES-417 appears in a damaged access log.</p></div>`)}
function personnel(){page(`<div class="paper"><h1>Personnel Record</h1><p><b>Name:</b> Evelyn Shaw</p><p><b>Department:</b> Research Staff</p><p><b>Credential:</b> ES-417</p><p><b>Status:</b> Active - Fall 2005</p><p><b>Authorized buildings:</b> Research offices; Lilly Hall shared facilities</p></div>`)}
function access(){page(`<div class="paper"><h1>Campus Access Summary - 24 NOV 2005</h1><table><tr><th>Person</th><th>Recorded interval</th><th>Record condition</th></tr><tr><td>Daniel Price</td><td>3:12 PM - 4:45 PM</td><td>Entry and departure supported</td></tr><tr><td>Jonah Reed</td><td>3:26 PM - 4:52 PM</td><td>Entry and departure supported</td></tr><tr><td>Evelyn Shaw</td><td>Entry 4:31 PM</td><td>Departure record unavailable</td></tr></table><p><b>Statement attached to Shaw's file:</b> "I left Lilly Hall around 4:55. The sun had not set yet, but it was getting low, so I knew I needed to leave for dinner."</p></div>`)}
function weather(){page(`<div class="paper"><div class="small">LAFAYETTE AREA HISTORICAL SOLAR TABLE // NOVEMBER 2005</div><h1>Sunrise and Sunset Record</h1><table><tr><th>Date</th><th>Sunrise</th><th>Sunset</th></tr><tr><td>Nov 21</td><td>7:40 AM</td><td>5:26 PM</td></tr><tr><td>Nov 22</td><td>7:41 AM</td><td>5:26 PM</td></tr><tr><td>Nov 23</td><td>7:42 AM</td><td>5:25 PM</td></tr><tr><td><b>Nov 24</b></td><td><b>7:43 AM</b></td><td><b>5:25 PM</b></td></tr><tr><td>Nov 25</td><td>7:44 AM</td><td>5:24 PM</td></tr><tr><td>Nov 26</td><td>7:45 AM</td><td>5:24 PM</td></tr></table><p class="small">Times shown in local Eastern Standard Time. Lafayette did not observe daylight saving time in 2005.</p></div>`)}
function chemistry(){page(`<div class="paper"><h1>Evidence Laboratory - Sample Results</h1><table><tr><th>Evidence</th><th>Description</th><th>Indicator result</th></tr><tr><td>B14</td><td>Residue recovered from cigar</td><td>BASIC</td></tr><tr><td>B19</td><td>Residue recovered from candle exterior</td><td>ACIDIC</td></tr></table><p>Refer to the printed toxicology and chemical reference sheets recovered at the scene.</p></div>`)}
const lockedFiles=[
{id:'report',name:'REPORT.DOC',password:'112505',body:`RESEARCH INTEGRITY DRAFT\n\nSubmission scheduled: Friday, 25 November 2005, 09:00.\n\nSubjects under review:\nE.S.\nD.P.\nJ.R.\n\nThe evidence is sufficient. I will not delay again.\n\n- A.V.`},
{id:'accesslog',name:'ACCESS_LOG.DAT',password:'ES417',body:`RECOVERED ACCESS FRAGMENT\n\n21 NOV 2005\n18:32 - Credential ES-417\nRestricted Teaching Collection\nCabinet F-12\n\nPOST-AUDIT: one accession entered discrepancy state.\n\n24 NOV 2005\n17:02 - administrative terminal opened\n17:24 - session ended\n\nRecord edits detected.`},
{id:'archive',name:'ARCHIVE_F12.LOG',password:'F12112105',body:`CABINET F-12 AUDIT\n\nAccession PUR-F-77421\nSpecies: Amanita phalloides\nStatus after 21 NOV audit: DISCREPANCY\n\nCross-reference: Credential ES-417.`}
];
function files(){page(`<div class="card"><h1>Encrypted Files</h1>${lockedFiles.map(f=>`<div class="lockbox"><h3>${f.name}</h3><input id="${f.id}-pw" type="password"><button onclick="unlockFile('${f.id}')">Decrypt</button><pre id="${f.id}-out"></pre></div>`).join('')}</div>`)}
window.unlockFile=id=>{let f=lockedFiles.find(x=>x.id===id),v=document.getElementById(id+'-pw').value.trim().toUpperCase(),o=document.getElementById(id+'-out');if(v===f.password){o.className='status-ok';o.textContent='\nACCESS GRANTED\n\n'+f.body}else{o.className='status-bad';o.textContent='\nACCESS DENIED'}};
function terminal(){page(`<div class="terminal"><h1>> CASE RESOLUTION TERMINAL</h1><p>Murderer:<br><select id="murderer"><option value="">-- SELECT --</option>${CASE.suspects.map(s=>`<option>${s}</option>`).join('')}</select></p><p>Person who carried out a separate attempt:<br><select id="attempted"><option value="">-- SELECT --</option>${CASE.suspects.map(s=>`<option>${s}</option>`).join('')}</select></p><p>Person who planned violence but did not act:<br><select id="planned"><option value="">-- SELECT --</option>${CASE.suspects.map(s=>`<option>${s}</option>`).join('')}</select></p><p>Role of cigar residue:<br><select id="cigar"><option value="">-- SELECT --</option><option value="staged">The cigar evidence was staged to redirect the timeline</option><option value="fatal">The cigar caused the fatal poisoning</option><option value="accident">The residue was accidental</option></select></p><button onclick="submitCase()">SUBMIT CASE</button><pre id="result"></pre></div>`)}
window.submitCase=()=>{let good=document.getElementById('murderer').value==='Dr. Evelyn Shaw'&&document.getElementById('attempted').value==='Daniel Price'&&document.getElementById('planned').value==='Jonah Reed'&&document.getElementById('cigar').value==='staged';let o=document.getElementById('result');o.className=good?'status-ok':'status-bad';o.textContent=good?'\n> CASE 112405 SOLVED.\n> ARCHIVE RELEASED.\n> RETURNING TO 2026...':'\n> THEORY REJECTED.\n> Review the evidence and try again.'}
function notFound(){page(`<div class="card"><h1>ARCHIVE ERROR</h1><p>Record unavailable.</p></div>`)}
function render(){let r=route(),routes={'/':home,'/phone':phone,'/purdue':purdue,'/purdue/fungarium':fungarium,'/purdue/personnel/eshaw':personnel,'/purdue/access':access,'/archive/weather':weather,'/forensics/chemistry':chemistry,'/files':files,'/terminal':terminal};(routes[r]||notFound)()}
render();
